### ISSUE TITLE
Small typo in a comment?

### ISSUE THREAD

**Issue by JoanEspasa** [arminbiere/satch#7]
Dear Armin,

It is nearly irrelevant, but I believe there might be a small typo in a comment ([features.h:73](https://github.com/arminbiere/satch/blob/6303d8d2d373e14eeb28aeaf58c13a6f36d9db1a/features.h#L73)), where NQUEUE should be replaced by NHEAP. 

Apologies if that is not the case, and thank you for this project!

**Comment by JoanEspasa** [comment]
As this is the first SAT solver that I'm trying to modify, I feel a bit overwhelmed when trying to get the "big picture" of how the codebase works. I was wondering if there is any document, paper or slides that explains the codebase a bit in detail for the uninitiated like me.

**Comment by arminbiere** [comment]
Thanks for spotting the typo.  Fixed in our internal version.  Then regarding additional material, please note that I wrote this solver particular for this purpose of explaining how those SAT solvers work, motivated by talks at the Simons Institutes.  You find 7 hours of video material as well as slides on my (old) talks homepage:
http://fmv.jku.at/biere/talks/index.html

**Comment by JoanEspasa** [comment]
Many thanks for the work and the pointers to the material!
